version: "2"

services:
  lb:
    image: dockercloud/haproxy
    depends_on:
      - voting-app
    ports:
      - "80:80"
      - "1936:1936"
    links:
      - voting-app
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH

  lt:
    build: ./load-testing/.
    volumes:
      - ./load-testing:/app
    ports:
      - "8089:8089"

  voting-app:
    build: ./voting-app/.
    volumes:
      - ./voting-app:/app
    ports:
      - "80"
    links:
      - redis
      - result-app

  result-app:
    build: ./result-app/.
    volumes:
      - ./result-app:/app
    ports:
      - "5001:80"
    links:
      - db

  worker:
    image: manomarks/worker
    links:
      - db

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    links:
      - worker

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data:
