version: "2"

services:
  voting-app:
    build: ./voting-app/.
    volumes:
     - ./voting-app:/app
    ports:
      - "5000:80"
    links:
      - redis
    networks:
      - front-tier
      - back-tier

  result-app:
    build: ./result-app/.
    volumes:
      - ./result-app:/app
    ports:
      - "5001:80"
    links:
      - db
    networks:
      - front-tier
      - back-tier

  test-app:
    build: ./test-app/.
    volumes:
     - ./test-app:/app/
    ports:
      - "5002:80"
    links:
      - voting-app
      - db
    environment:
      - TESTAPP_VOTING_HOST=voting-app
      - TESTAPP_VOTING_PORT=80
      - TESTAPP_POSTGRES_HOST=db
      - TESTAPP_POSTGRES_PORT=5432      
    networks:
      - front-tier  
      - back-tier

  worker:
    image: manomarks/worker
    links:
      - db
      - redis
    networks:
      - back-tier

  redis:
    image: redis:alpine
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
