version: "2"

services:
# Our app
  voting-app:
    image: lalu/votingapp_voting-app
    ports:
      - "5000:80"
    environment:
      - "constraint:type==node"
    networks:
      - front-tier
      - back-tier

  result-app:
    image: lalu/votingapp_result-app
    ports:
      - "5001:80"
    environment:
      - "constraint:type==node"
    networks:
      - front-tier
      - back-tier

  worker:
    image: manomarks/worker
    container_name: worker
    environment:
      - "constraint:type==node"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379"
    environment:
      - "constraint:type==node"
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      - "constraint:type==node"
    networks:
      - back-tier

  lb:
    image: dockercloud/haproxy
    links:
      - voting-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - front-tier


volumes:
  db-data:

networks:
  front-tier:
  back-tier:
